// Fetch user
export const ACCOUNT_SIGNUP_REQUEST = "ACCOUNT_SIGNUP_REQUEST"
export const ACCOUNT_SIGNUP_SUCCESS = "ACCOUNT_SIGNUP_SUCCESS"
export const ACCOUNT_SIGNUP_FAIL  = "ACCOUNT_SIGNUP_FAIL"

//Update user
export const ACCOUNT_UPDATE_REQUEST = "ACCOUNT_SAVE_REQUEST"
export const ACCOUNT_UPDATE_SUCCESS = "ACCOUNT_SAVE_SUCCESS"
export const ACCOUNT_UPDATE_FAIL  = "ACCOUNT_SAVE_FAIL"

//Sign in
export const ACCOUNT_SIGNIN_REQUEST = "ACCOUNT_SIGNIN_REQUEST"
export const ACCOUNT_SIGNIN_SUCCESS = "ACCOUNT_SIGNIN_SUCCESS"
export const ACCOUNT_SIGNIN_FAIL  = "ACCOUNT_SIGNIN_FAIL"


//Fetch user information
export const USERINFO_FETCH_REQUEST = "USERINFO_FETCH_REQUEST"
export const USERINFO_FETCH_SUCCESS = "USERINFO_FETCH_SUCCESS"
export const USERINFO_FETCH_FAIL = "USERINFO_FETCH_FAIL"

export const ACCOUNT_SIGNOUT  = "ACCOUNT_SIGNOUT"


