// Fetch user
export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST"
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS"
export const USER_SIGNUP_FAIL  = "USER_SIGNUP_FAIL"

//Update user
export const USER_UPDATE_REQUEST = "USER_SAVE_REQUEST"
export const USER_UPDATE_SUCCESS = "USER_SAVE_SUCCESS"
export const USER_UPDATE_FAIL  = "USER_SAVE_FAIL"

//Sign in
export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST"
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS"
export const USER_SIGNIN_FAIL  = "USER_SIGNIN_FAIL"

export const USER_SIGNOUT  = "USER_SIGNOUT"


