// Fetch user


//Sign in
export const ACCOUNT_SIGNIN_REQUEST = "ACCOUNT_SIGNIN_REQUEST"
export const ACCOUNT_SIGNIN_SUCCESS = "ACCOUNT_SIGNIN_SUCCESS"
export const ACCOUNT_SIGNIN_FAIL  = "ACCOUNT_SIGNIN_FAIL"


//Fetch user information
export const USERINFO_FETCH_REQUEST = "USERINFO_FETCH_REQUEST"
export const USERINFO_FETCH_SUCCESS = "USERINFO_FETCH_SUCCESS"
export const USERINFO_FETCH_FAIL = "USERINFO_FETCH_FAIL"

export const ACCOUNT_SIGNOUT  = "ACCOUNT_SIGNOUT"


